title: Matt's Weblog
description: >
  Matt Rugamas (@MatthewRugamas): Designer and Frontend Dev Student
url: "https://samagurtam.github.io/"
permalink: /:title # Don't show the date of the post in the URL

# Social
twitter_username: matthewrugamas
github_username: samagurtam

# Build settings
repository: samagurtam/samagurtam.github.io
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap # I added this to automatically generate a sitemap.xml
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
