title: Matt's Weblog
description: >
  Matt Rugamas (@MatthewRugamas): Designer and Frontend Dev Student
url: "https://www.mattrugamas.com"
permalink: /:title

# Google Analytics
google_analytics: UA-131785558-1

# Social
twitter_username: MattRugamas
instagram_username: MattRugamas
github_username: MattRugamas
codepen_username: samagurtam

# Build settings
repository: MattRugamas/mattrugamas.com
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - rouge
  - jekyll-tidy
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
