title: Matthew's Weblog
description: >
  A personal site for showcasing ideas and projects.
url: "https://samagurtam.github.io"
show_excerpts: true
permalink: /:categories/:title # Don't show the date of the post in the URL

# Social
twitter_username: matthewrugamas
github_username: samagurtam

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap # I added this to automatiacally generate a sitemap.xml
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"