title: Matt's Weblog
description: >
  Matt Rugamas (@MatthewRugamas): Designer and Frontend Dev Student
url: "https://samagurtam.github.io/"
permalink: /:title # Don't show the date of the post in the URL

# Google Analytics
google_analytics: UA-131785558-1

# Social
twitter_username: matthewrugamas
github_username: samagurtam

# Build settings
repository: samagurtam/samagurtam.github.io
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - rouge
  - jekyll-tidy
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
