title: Matt Rugamas (@mattrugamas)
description: >
  A web builder based in Los Angeles
url: mattrugamas.com
permalink: /:title

# SASS/SCSS
sass:
  style: compressed

# Google Analytics
google_analytics: UA-131785558-1

# Social
twitter_username: MattRugamas
instagram_username: MattRugamas
github_username: MattRugamas
codepen_username: samagurtam

# Build settings
repository: MattRugamas/mattrugamas.com
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - rouge
  - jekyll-tidy
  - jekyll-figure
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Plugin Settings
jekyll-figure:
  paragraphs: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
